definitions:
  models.Memo:
    properties:
      body:
        type: string
      created_at:
        type: string
      id:
        type: integer
      title:
        type: string
      updated_at:
        type: string
    type: object
info:
  contact: {}
paths:
  /memos/{id}:
    get:
      consumes:
      - application/json
      description: Get memos
      operationId: get-memos
      parameters:
      - description: Memo ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Memo'
        "400":
          description: Bad Request
        "404":
          description: Not Found
      summary: Get memos
swagger: "2.0"
